[[opener.set-wallpaper]]
run = 'sh -c "/usr/bin/hyprctl hyprpaper preload %s; sleep 0.1; /usr/bin/hyprctl hyprpaper wallpaper ,%s"'
desc = "Set as wallpaper"


[[open.prepend_rules]]
mime = "image/*"
use  = [ "set-wallpaper", "open" ]  