[[opener.set-wallpaper]]
run = "bash /home/simonkdev/nixsys/home-manager/modules/devtools/set-wallp.sh /home/simonkdev/nixsys/wallpapers/wallpaper.jpg"
desc = "Set as wallpaper"


[[open.prepend_rules]]
mime = "image/*"
use  = [ "set-wallpaper", "open" ]  