[[opener.set-wallpaper]]
run  = 'sh -c "hyprctl hyprpaper preload %s && hyprctl hyprpaper wallpaper ,%s"'
desc = "Set as wallpaper"


[[open.prepend_rules]]
mime = "image/*"
use  = [ "set-wallpaper", "open" ]  